import test from 'node:test';import assert from 'node:assert/strict';
import {BrowserStore} from '../src/core/store.js';import {seed} from '../src/core/seed.js';import {AuditBox} from '../src/boxes/audit-box.js';import {WorkService} from '../src/work/work-service.js';import {MultiAgentRuntime} from '../src/work/multi-agent-runtime.js';import {ImportService,parseCSV} from '../src/import/import-service.js';import {ProvisioningService} from '../src/import/provisioning-service.js';
const make=()=>{const s=new BrowserStore(`test-${Math.random()}`); for(const k of ['users','roles','capabilities','agents','workItems','personnel','students','facilities','assets','inventory','importBatches','provisioningQueue','audit','traces'])s.set(k,structuredClone(seed[k]||[])); const audit=new AuditBox(s);return{s,audit};};
test('CSV parser handles headers and rows',()=>{const r=parseCSV('a,b\n1,2\n3,4');assert.equal(r.length,2);assert.equal(r[1].b,'4');});
test('personnel import validates email and creates provisioning queue',()=>{const {s,audit}=make();const imp=new ImportService(s,audit);const rows=imp.validate('PERSONNEL',imp.normalize('PERSONNEL',[{employeeCode:'CB9',fullName:'Demo',email:'d@x.vn',unit:'U',position:'Giang vien'}]));const b=imp.commit({type:'PERSONNEL',rows,userId:'USR-ADMIN',fileName:'p.csv'});assert.equal(b.valid,1);assert.equal(s.get('provisioningQueue',[]).length,1);assert.equal(s.get('provisioningQueue',[])[0].suggestedRole,'LECTURER');});
test('invalid personnel record is not committed',()=>{const {s,audit}=make();const before=s.get('personnel',[]).length;const imp=new ImportService(s,audit);const rows=imp.validate('PERSONNEL',imp.normalize('PERSONNEL',[{employeeCode:'CB10',fullName:'No Mail'}]));const b=imp.commit({type:'PERSONNEL',rows,userId:'USR-ADMIN',fileName:'p.csv'});assert.equal(b.invalid,1);assert.equal(s.get('personnel',[]).length,before);});
test('provisioning creates account only after explicit action',()=>{const {s,audit}=make();s.set('provisioningQueue',[{id:'P1',sourceType:'STUDENT',sourceId:'S1',displayName:'Student X',email:'sx@anu.vn',suggestedRole:'STUDENT',suggestedTier:3,suggestedScope:'PROGRAM-AI',status:'PENDING'}]);const p=new ProvisioningService(s,audit);const u=p.createAccount('P1','USR-ADMIN');assert.equal(u.assignments[0].role,'STUDENT');assert.equal(p.queue()[0].status,'CREATED');});
test('work assignment cannot delegate capabilities outside agent profile',()=>{const {s}=make();const w=new WorkService(s,s.get('agents'));const item=w.create({title:'T',purpose:'P',humanOwner:'USR-EXEC',scope:{type:'UNIVERSITY',id:'ANU'}});w.assign(item.id,{agentId:'data-agent',task:'x',capabilities:['data.analyze','decision.prepare'],actions:['READ','APPROVE']});const saved=w.get(item.id).assignments[0];assert.deepEqual(saved.capabilities,['data.analyze']);assert.deepEqual(saved.actions,['READ']);});
test('multi-agent runtime stores output and trace',async()=>{const {s,audit}=make();const w=new WorkService(s,s.get('agents'));const item=w.create({title:'T',purpose:'P',humanOwner:'USR-EXEC',scope:{type:'UNIVERSITY',id:'ANU'}});w.assign(item.id,{agentId:'data-agent',task:'analyze',capabilities:['data.analyze'],actions:['READ','ANALYZE']});const model={reason:async()=>({text:'result',provider:'mock',model:'mock'})};const rt=new MultiAgentRuntime({store:s,model,agents:s.get('agents'),capabilities:s.get('capabilities'),audit});await rt.runReady({workId:item.id,human:{id:'USR-EXEC'},userContext:{role:'VICE_RECTOR'}});assert.equal(w.get(item.id).outputs.length,1);assert.equal(s.get('traces',[]).length,1);});
