const trim=v=>typeof v==='string'?v.trim():v;
export function parseCSV(text){
  const rows=[]; let row=[],cell='',q=false;
  for(let i=0;i<text.length;i++){ const ch=text[i],n=text[i+1]; if(ch==='"'&&q&&n==='"'){cell+='"';i++;continue;} if(ch==='"'){q=!q;continue;} if(ch===','&&!q){row.push(cell);cell='';continue;} if((ch==='\n'||ch==='\r')&&!q){ if(ch==='\r'&&n==='\n')i++; row.push(cell); cell=''; if(row.some(x=>x!=='')) rows.push(row); row=[]; continue;} cell+=ch; }
  if(cell||row.length){row.push(cell);rows.push(row);} if(!rows.length)return[]; const headers=rows[0].map(h=>String(h).trim()); return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,trim(r[i]??'')])));
}
const pick=(o,keys)=>{ for(const k of keys){ if(o[k]!=null&&String(o[k]).trim()!=='') return trim(o[k]); } return ''; };
export class ImportService {
  constructor(store,audit){ this.store=store; this.audit=audit; }
  async readFile(file){ const name=file.name.toLowerCase(); if(name.endsWith('.json')) return JSON.parse(await file.text()); if(name.endsWith('.csv')) return parseCSV(await file.text()); throw new Error('Bản thử nghiệm V3 hỗ trợ CSV và JSON. Hãy lưu Excel thành CSV trước khi nhập.'); }
  normalize(type,rows){ const arr=Array.isArray(rows)?rows:(rows?.records||[]); return arr.map((r,i)=>{
    if(type==='PERSONNEL') return {id:pick(r,['id','employeeCode','ma_can_bo'])||`PER-${Date.now()}-${i}`,employeeCode:pick(r,['employeeCode','ma_can_bo','mã cán bộ']),fullName:pick(r,['fullName','ho_ten','họ tên','name']),email:pick(r,['email','mail']),unit:pick(r,['unit','don_vi','đơn vị']),position:pick(r,['position','chuc_vu','chức vụ']),status:pick(r,['status','trang_thai'])||'ACTIVE',source:'import'};
    if(type==='STUDENT') return {id:pick(r,['id','studentCode','ma_sv'])||`STU-${Date.now()}-${i}`,studentCode:pick(r,['studentCode','ma_sv','mã sinh viên']),fullName:pick(r,['fullName','ho_ten','họ tên','name']),email:pick(r,['email','mail']),program:pick(r,['program','chuong_trinh']),faculty:pick(r,['faculty','khoa']),cohort:pick(r,['cohort','khoa_hoc']),status:pick(r,['status','trang_thai'])||'ACTIVE',source:'import'};
    if(type==='ORGANIZATION') return {id:pick(r,['id','code','ma_don_vi','mã đơn vị'])||`ORG-${Date.now()}-${i}`,code:pick(r,['code','ma_don_vi','mã đơn vị']),name:pick(r,['name','ten','tên','ten_don_vi']),type:(pick(r,['type','loai','loại'])||'UNIT').toUpperCase(),parentId:pick(r,['parentId','parent','don_vi_cap_tren','đơn vị cấp trên']),mission:pick(r,['mission','su_menh','sứ mệnh']),functions:pick(r,['functions','chuc_nang','chức năng']).split(/[;|]/).map(x=>x.trim()).filter(Boolean),responsibilities:pick(r,['responsibilities','nhiem_vu','nhiệm vụ']).split(/[;|]/).map(x=>x.trim()).filter(Boolean),managerRole:pick(r,['managerRole','vai_tro_quan_ly','vai trò quản lý'])||'DEPARTMENT_HEAD',status:pick(r,['status','trang_thai'])||'ACTIVE'};
    if(type==='FACILITY') return {id:pick(r,['id','code','ma'])||`FAC-${Date.now()}-${i}`,type:(pick(r,['type','loai'])||'BUILDING').toUpperCase(),name:pick(r,['name','ten','tên']),campus:pick(r,['campus','co_so']),buildingId:pick(r,['buildingId','toa_nha']),floor:Number(pick(r,['floor','tang'])||0),area:Number(pick(r,['area','dien_tich'])||0),grossArea:Number(pick(r,['grossArea','tong_dien_tich'])||0),usableArea:Number(pick(r,['usableArea','dien_tich_su_dung'])||0),status:pick(r,['status','trang_thai'])||'ACTIVE'};
    if(type==='ASSET') return {id:pick(r,['id','assetCode','ma_tai_san'])||`AST-${Date.now()}-${i}`,assetCode:pick(r,['assetCode','ma_tai_san']),name:pick(r,['name','ten']),category:pick(r,['category','nhom']),location:pick(r,['location','vi_tri']),ownerUnit:pick(r,['ownerUnit','don_vi']),condition:pick(r,['condition','tinh_trang'])||'GOOD',status:pick(r,['status','trang_thai'])||'ACTIVE'};
    return {id:pick(r,['id','itemCode','ma_vat_tu'])||`INV-${Date.now()}-${i}`,itemCode:pick(r,['itemCode','ma_vat_tu']),name:pick(r,['name','ten']),category:pick(r,['category','nhom']),unit:pick(r,['unit','don_vi_tinh']),quantityOnHand:Number(pick(r,['quantityOnHand','so_luong'])||0),minimumLevel:Number(pick(r,['minimumLevel','ton_toi_thieu'])||0),warehouse:pick(r,['warehouse','kho']),status:pick(r,['status','trang_thai'])||'ACTIVE'};
  }); }
  validate(type,rows){ return rows.map((r,i)=>{ const errors=[]; if(!r.name&&!r.fullName)errors.push('Thiếu tên'); if(type==='ORGANIZATION'&&!r.code)errors.push('Thiếu mã đơn vị'); if(type==='PERSONNEL'&&!r.employeeCode)errors.push('Thiếu mã cán bộ'); if(type==='STUDENT'&&!r.studentCode)errors.push('Thiếu mã sinh viên'); if(['PERSONNEL','STUDENT'].includes(type)&&!r.email)errors.push('Thiếu email'); return {...r,_row:i+2,_errors:errors}; }); }
  commit({type,rows,userId,fileName}){ const map={PERSONNEL:'personnel',STUDENT:'students',ORGANIZATION:'organizations',FACILITY:'facilities',ASSET:'assets',INVENTORY:'inventory'}; const key=map[type]; const valid=rows.filter(r=>!r._errors?.length).map(({_errors,_row,...x})=>x); const existing=this.store.get(key,[]); const idField={PERSONNEL:'employeeCode',STUDENT:'studentCode',ORGANIZATION:'code',FACILITY:'id',ASSET:'assetCode',INVENTORY:'itemCode'}[type]; const merged=[...existing]; for(const r of valid){ const i=merged.findIndex(x=>String(x[idField]||x.id)===String(r[idField]||r.id)); if(i>=0) merged[i]={...merged[i],...r}; else merged.push(r); } this.store.set(key,merged);
    const batch={id:`IMP-${Date.now()}`,type,fileName,records:rows.length,valid:valid.length,invalid:rows.length-valid.length,createdBy:userId,createdAt:new Date().toISOString(),status:'COMPLETED'}; const batches=this.store.get('importBatches',[]); batches.unshift(batch); this.store.set('importBatches',batches);
    if(['PERSONNEL','STUDENT'].includes(type)){ const q=this.store.get('provisioningQueue',[]); for(const r of valid){ q.unshift({id:`PROV-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,sourceType:type,sourceId:r.id,displayName:r.fullName,email:r.email,suggestedRole:type==='STUDENT'?'STUDENT':this.suggestRole(r.position),suggestedTier:type==='STUDENT'?3:this.suggestTier(r.position),suggestedScope:type==='STUDENT'?(r.program||r.faculty||'PUBLIC'):(r.unit||'UNIVERSITY'),status:'PENDING'}); } this.store.set('provisioningQueue',q); }
    this.audit.record({actorId:userId,action:'IMPORT_COMMIT',resourceId:batch.id,type,records:valid.length}); return batch;
  }
  suggestRole(position=''){ const p=String(position).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); if(p.includes('hieu truong'))return p.includes('pho')?'VICE_RECTOR':'RECTOR'; if(p.includes('truong khoa')||p.includes('truong phong')||p.includes('truong don vi'))return'DEPARTMENT_HEAD'; if(p.includes('giang vien'))return'LECTURER'; return'STAFF'; }
  suggestTier(position=''){ const role=this.suggestRole(position); return ['RECTOR','VICE_RECTOR'].includes(role)?1:role==='DEPARTMENT_HEAD'?2:3; }
}
