import {BrowserStore} from './core/store.js';
import {seed} from './core/seed.js';
import {IdentityBox} from './boxes/identity-box.js';
import {ContextBox} from './boxes/context-box.js';
import {AuditBox} from './boxes/audit-box.js';
import {ModelGatewayBox} from './boxes/model-gateway-box.js';
import {WorkService} from './work/work-service.js';
import {MultiAgentRuntime} from './work/multi-agent-runtime.js';
import {ImportService} from './import/import-service.js';
import {ProvisioningService} from './import/provisioning-service.js';
import {I18nService} from './core/i18n-service.js';
import {migrateStore} from './core/migrate.js';
import {PasswordRecoveryBox} from './boxes/password-recovery-box.js';
import {menuForRole,canConfigureAI} from './core/ui-config.js';
import {DOMAIN_REGISTRY,labelDomain,domainCounts} from './domains/domain-registry.js';
import {ArtifactStore} from './artifacts/artifact-store.js';
import {SpeechInputService,speechSupported} from './input/speech-input-service.js';
import {MultimodalProcessor} from './input/multimodal-processor.js';

const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const store=new BrowserStore('anu2-v3');
migrateStore(store,seed,{version:'5.2.0'});
const audit=new AuditBox(store); const identity=new IdentityBox(store,seed); const contextBox=new ContextBox(store,audit); const model=new ModelGatewayBox();
const work=new WorkService(store,store.get('agents',[])); const multi=new MultiAgentRuntime({store,model,agents:store.get('agents',[]),capabilities:store.get('capabilities',[]),audit});
const importer=new ImportService(store,audit); const provisioning=new ProvisioningService(store,audit); const recovery=new PasswordRecoveryBox(store); const artifacts=new ArtifactStore(store); const speech=new SpeechInputService(); const multimodal=new MultimodalProcessor({artifacts,model});
const state={user:null,view:'dashboard',selectedWork:null,importPreview:null,importType:'PERSONNEL',importFileName:'',lang:'vi',selectedDomain:'OIS',workInputSource:'TEXT',importInputSource:'TEXT'};
const i18n=new I18nService({defaultLang:'vi'});
const t=(key,vars)=>i18n.t(key,vars);
const roleLabel=r=>{const x=t(`roles.${r}`);if(!x.startsWith('['))return x;const found=identity.roles().find(z=>z.id===r);return found?.label?.[i18n.lang]||found?.label?.vi||r;};
function speechLocale(){return i18n.lang==='zh-CN'?'zh-CN':i18n.lang==='en'?'en-US':'vi-VN';}
function ctx(){ return state.user?contextBox.active(state.user):null; } function role(){ return ctx()?.role||''; } function isAdmin(){return role()==='SYSTEM_ADMIN';}
function card(title,body,cls=''){return `<section class="card ${cls}"><h3>${esc(title)}</h3>${body}</section>`}
function badge(s){return `<span class="badge ${String(s).toLowerCase()}">${esc(s)}</span>`}
function statusVi(s){const x=t(`status.${s}`);return x.startsWith('[')?s:x;}
function login(){document.body.innerHTML=`<main class="login"><div class="login-card"><div class="brand">${t('app.name')} <b>${t('app.version')}</b></div><h1>${t('login.title')}</h1><p>${t('login.subtitle')}</p><label>${t('login.username')}<input id="u" value="admin"></label><label>${t('login.password')}<input id="p" type="password" value="Admin123!"></label><button id="login" class="primary">${t('login.submit')}</button><button id="forgot" class="link">${t('login.forgot')}</button><details><summary>${t('login.demo')}</summary><div class="demo-list">admin / Admin123!<br>rector / Rector123!<br>executive / Executive123!<br>manager / Manager123!<br>lecturer / Lecturer123!<br>researcher / Research123!<br>student / Student123!<br>staff / Staff123!<br>multirole / MultiRole123!</div></details></div></main>`; i18n.translateDOM(document.body); $('#login').onclick=()=>{const u=identity.authenticate($('#u').value.trim(),$('#p').value); if(!u)return alert(t('login.invalid')); state.user=u; state.view='dashboard'; render();}; $('#forgot').onclick=()=>forgotPassword();}
async function forgotPassword(){const identifier=prompt(t('recovery.identifier')); if(!identifier)return; const channel=(prompt(t('recovery.channel'),'email')||'email').toLowerCase()==='sms'?'sms':'email'; try{const r=await recovery.request({identifier,channel}); if(r.delivered){alert(`${t('recovery.sent')} ${r.masked}`); return;} if(r.demoToken){const newPassword=prompt(`${t('recovery.demo')}
${r.demoToken}
${t('recovery.newPassword')}`); if(newPassword){recovery.reset({token:r.demoToken,newPassword}); alert(t('recovery.changed'));}} else alert(r.message||t('recovery.sent'));}catch(e){alert(e.message);}}
function shell(content){ const c=ctx(); const menu=menuForRole(c.role); document.body.innerHTML=`<div class="app"><aside><div class="logo">${t('app.name')} <small>${t('app.version')}</small></div><nav>${menu.map(([v,k])=>`<button data-view="${v}" class="${state.view===v?'active':''}">${esc(t(k))}</button>`).join('')}</nav><div class="side-foot">${esc(state.user.displayName)}<button id="logout">${t('common.logout')}</button></div></aside><main class="main"><header><div class="context-header"><select id="context" aria-label="${t('context.workingAs')}">${state.user.assignments.map(a=>`<option value="${a.id}" ${a.id===c.id?'selected':''}>${esc(roleLabel(a.role))} · ${esc(a.scope.id)}</option>`).join('')}</select></div><div class="top-actions"><select id="lang" aria-label="${t('common.language')}"><option value="vi" ${i18n.lang==='vi'?'selected':''}>VI</option><option value="en" ${i18n.lang==='en'?'selected':''}>EN</option><option value="zh-CN" ${i18n.lang==='zh-CN'?'selected':''}>中文</option></select><span>${new Date().toLocaleDateString(i18n.lang==='zh-CN'?'zh-CN':i18n.lang==='en'?'en-US':'vi-VN')}</span></div></header><div class="content">${content}</div></main></div>`;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.selectedWork=null;render()}); $('#context').onchange=e=>{contextBox.switch(state.user,e.target.value);state.view='dashboard';render()}; $('#lang').onchange=async e=>{await i18n.setLanguage(e.target.value);state.lang=i18n.lang;render()}; $('#logout').onclick=()=>{state.user=null;login()}; bind(); i18n.translateDOM(document.body); }
function pageHead(title,sub=''){return `<div class="page-head"><div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div></div>`}
function kpi(label,value,note=''){return `<div class="kpi"><span>${esc(label)}</span><b>${esc(value)}</b>${note?`<small>${esc(note)}</small>`:''}</div>`}
function visibleWork(){ const c=ctx(); const all=work.list(); if(isAdmin()||c.tier===1)return all; return all.filter(w=>w.humanOwner===state.user.id||w.scope?.id===c.scope?.id); }
function workRows(items=visibleWork()){return items.map(w=>`<tr><td><button class="link" data-open-work="${w.id}">${esc(w.title)}</button></td><td>${esc(w.priority)}</td><td>${badge(statusVi(w.status))}</td><td>${esc(w.deadline||'—')}</td><td>${w.assignments?.length||0} AI</td></tr>`).join('')||`<tr><td colspan="5" class="muted">Chưa có công việc.</td></tr>`;}
function dashboard(){ const r=role(); const works=visibleWork(); const waiting=works.filter(w=>w.status==='WAITING_FOR_HUMAN').length; if(r==='SYSTEM_ADMIN'){const pq=store.get('provisioningQueue',[]).filter(x=>x.status==='PENDING').length; const sys=works.find(w=>w.id==='WORK-SYS-GOV'); return pageHead('Tổng quan hệ thống','Con người và AI cùng quản trị dữ liệu, truy cập và vận hành hệ thống')+`<div class="kpis">${kpi('Người dùng',identity.list().length)}${kpi('Chờ tạo tài khoản',pq)}${kpi('Dữ liệu đầu vào',store.get('artifacts',[]).length)}${kpi('Công việc AI đang tham gia',works.filter(w=>w.status==='IN_PROGRESS').length)}</div>`+card('AI cùng quản trị',sys?`<div class="assignment"><div><b>${esc(sys.title)}</b><p>${esc(sys.purpose)}</p><small>${sys.assignments.length} AI được ủy quyền · ${esc(sys.status)}</small></div><button class="primary" data-open-work="${sys.id}">Mở công việc</button></div>`:'<p class="muted">Chưa có công việc quản trị cùng AI.</p>')+card('Cần xử lý',`<div class="action-list"><button data-view="imports">Nhập dữ liệu & tài liệu</button><button data-view="accounts">Người dùng & quản trị</button><button data-view="domains">Miền vận hành</button><button data-view="audit">Kiểm tra nhật ký hệ thống</button></div>`)+card('Công việc gần đây',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works.slice(0,6))}</table>`);}
 if(['RECTOR','VICE_RECTOR'].includes(r)) return pageHead('Tổng quan nhà trường','Tập trung vào công việc cần quyết định, rủi ro và tiến độ')+`<div class="kpis">${kpi('Cần tôi xử lý',waiting)}${kpi('Đang cùng AI thực hiện',works.filter(w=>w.status==='IN_PROGRESS').length)}${kpi('Đề tài đang theo dõi',3)}${kpi('Cảnh báo dữ liệu',dataIssues().length)}</div>`+card('Việc cần xử lý hôm nay',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works.slice(0,6))}</table>`)+card('Tình hình nổi bật',`<div class="grid2"><div><b>Nghiên cứu</b><p>3 đề tài trọng điểm đang hoạt động.</p></div><div><b>Dữ liệu & nguồn lực</b><p>${dataIssues().length} vấn đề dữ liệu cần chú ý.</p></div></div>`);
 if(r==='DEPARTMENT_HEAD') return pageHead('Tổng quan đơn vị','Công việc, nhân sự, dữ liệu và các việc chờ xử lý')+`<div class="kpis">${kpi('Công việc đang thực hiện',works.length)}${kpi('Chờ xử lý',waiting)}${kpi('Nhân sự trong dữ liệu',store.get('personnel',[]).filter(p=>p.unit===ctx().scope.id).length)}${kpi('Vấn đề dữ liệu',dataIssues().length)}</div>`+card('Công việc của đơn vị',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works)}</table>`);
 if(r==='LECTURER') return pageHead('Công việc giảng dạy','Các lớp học, nhiệm vụ và công việc đang thực hiện')+`<div class="kpis">${kpi('Lớp hôm nay',2)}${kpi('Bài cần xử lý',14)}${kpi('Sinh viên cần hỗ trợ',3)}${kpi('Công việc đang thực hiện',works.length)}</div>`+card('Hôm nay',`<div class="timeline"><div><b>08:00</b> Lớp AI cơ sở</div><div><b>13:30</b> Hướng dẫn đồ án</div><div><b>16:00</b> Xử lý phản hồi sinh viên</div></div>`)+card('Công việc có AI cùng thực hiện',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works)}</table>`);
 if(r==='RESEARCHER') return pageHead('Không gian nghiên cứu','Đề tài, bằng chứng, phân tích và công việc tiếp theo')+`<div class="kpis">${kpi('Đề tài đang thực hiện',2)}${kpi('Nguồn bằng chứng',12)}${kpi('Phân tích đang chờ',2)}${kpi('Công việc có AI tham gia',works.length)}</div>`+card('Đề tài đang thực hiện',`<div class="project"><b>AI trong giáo dục kỹ thuật</b><span>Tiến độ 68%</span><div class="progress"><i style="width:68%"></i></div></div>`)+card('Công việc',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works)}</table>`);
 if(r==='STUDENT') return pageHead('Trang chủ','Nhiệm vụ học tập và tiến độ của bạn')+`<div class="kpis">${kpi('Bài tập cần nộp',2)}${kpi('Buổi học hôm nay',1)}${kpi('Tiến độ học kỳ','64%')}${kpi('Nhiệm vụ cá nhân',works.length)}</div>`+card('Hôm nay',`<div class="timeline"><div><b>09:00</b> Học máy</div><div><b>17:00</b> Hạn nộp bài tập</div></div>`)+card('Công việc đang thực hiện',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works)}</table>`);
 return pageHead('Công việc hôm nay','Hồ sơ, nhiệm vụ và dữ liệu cần xử lý')+`<div class="kpis">${kpi('Hồ sơ chờ xử lý',7)}${kpi('Việc hôm nay',4)}${kpi('Quá hạn',1)}${kpi('Công việc có AI tham gia',works.length)}</div>`+card('Công việc',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(works)}</table>`);
}
function workView(){ if(state.selectedWork)return workDetail(state.selectedWork); return pageHead('Công việc','Con người và AI cùng thực hiện trong phạm vi được ủy quyền')+card('Tạo công việc mới',`<div class="form-grid"><label>Tên công việc<input id="w-title"></label><label>Mục tiêu<input id="w-purpose"></label><label>Miền<select id="w-domain">${DOMAIN_REGISTRY.map(d=>`<option value="${d.id}">${esc(labelDomain(d.id,i18n.lang))}</option>`).join('')}</select></label><label>Phạm vi<input id="w-scope" value="${esc(ctx().scope.id)}"></label><label>Hạn<input id="w-deadline" type="date"></label></div><button id="create-work" class="primary">Tạo công việc</button>`)+card('Danh sách công việc',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows()}</table>`);}
function workDetail(id){
 const w=work.get(id); if(!w)return workView();
 const agents=store.get('agents',[]).filter(a=>a.status==='ACTIVE');
 const attached=store.get('artifacts',[]).filter(a=>(w.artifactIds||[]).includes(a.id));
 const provider=model.publicConfig(); const canSpeak=speechSupported();
 const inputCard=card('Dữ liệu đầu vào & yêu cầu cho AI',`
   <div class="human-ai-input">
     <div class="speech-row">
       <button id="speech-start" class="speech-button" ${canSpeak?'':'disabled'}>🎙 Nói trực tiếp</button>
       <button id="speech-stop" class="small" disabled>Dừng</button>
       <span id="speech-status" class="muted">${canSpeak?'Sẵn sàng nhận giọng nói':'Trình duyệt chưa hỗ trợ nhận dạng giọng nói trực tiếp'}</span>
     </div>
     <label>Yêu cầu cho AI
       <textarea id="work-request" rows="5" placeholder="Nói trực tiếp hoặc nhập yêu cầu: ví dụ 'Đọc các tài liệu đã tải lên, tóm tắt vấn đề chính và đề xuất 3 việc cần xử lý'."></textarea>
     </label>
     <div id="speech-interim" class="speech-interim"></div>
     <label class="file-drop">Thêm tài liệu, hình ảnh, âm thanh hoặc video
       <input id="work-files" type="file" multiple accept="image/*,audio/*,video/*,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.json,.txt,.md">
     </label>
     <div class="artifact-grid">${attached.map(a=>`<div class="artifact"><b>${esc(a.name)}</b><span>${esc(a.mediaType)} · ${Math.round((a.size||0)/1024)} KB</span><small>${esc(a.processingStatus)}</small>${a.processingStatus==='AI_PROCESSED'?`<small>AI đã xử lý nội dung</small>`:a.textPreview?`<small>Đã có nội dung văn bản cho AI</small>`:`<small>${esc(a.processingError||'Chưa xử lý nội dung')}</small>`}<div class="processor-state"><button class="small" data-process-artifact="${a.id}">AI xử lý tệp</button></div></div>`).join('')||'<p class="muted">Chưa có dữ liệu đính kèm.</p>'}</div>
     <div class="assist-row">
       <button id="assist-work" class="primary">Gửi yêu cầu cho AI đang tham gia</button>
       <span class="muted">AI hiện tại: ${esc(provider.provider)} / ${esc(provider.model)}</span>
     </div>
     <p class="multimodal-note">V5.2 xử lý đa phương tiện theo provider đang cấu hình. TXT/MD/CSV/JSON được đọc cục bộ; Gemini có thể xử lý trực tiếp PDF/image/audio/video và các MIME được model hỗ trợ; OpenAI/OpenRouter xử lý ảnh, OpenAI có thể phiên âm audio. Nếu provider không hỗ trợ loại tệp, hệ thống báo lỗi rõ ràng thay vì giả lập đã đọc.</p>
   </div>`);
 const history=(w.requests||[]).slice(0,6).map(r=>`<div class="request-history"><b>${esc(r.source==='VOICE'?'🎙 Yêu cầu bằng lời nói':'Yêu cầu của con người')}</b><p>${esc(r.text)}</p><small>${new Date(r.createdAt).toLocaleString(i18n.lang==='zh-CN'?'zh-CN':i18n.lang==='en'?'en-US':'vi-VN')}</small></div>`).join('');
 return `<button class="back" id="back-work">← Danh sách công việc</button>${pageHead(w.title,w.purpose)}<div class="kpis">${kpi('Miền',labelDomain(w.domain||'OIS',i18n.lang))}${kpi('Trạng thái',statusVi(w.status))}${kpi('AI được phân công',w.assignments.length)}${kpi('Dữ liệu đính kèm',attached.length)}</div>${card('Con người chịu trách nhiệm',`<p>${esc(identity.get(w.humanOwner)?.displayName||w.humanOwner)}</p><p class="muted">Phạm vi: ${esc(w.scope?.id)}</p>`)}${inputCard}${history?card('Yêu cầu gần đây',history):''}${card('AI đang cùng thực hiện',w.assignments.map(a=>{const ag=agents.find(x=>x.id===a.agentId);return `<div class="assignment"><div><b>${esc(ag?.name||a.agentId)}</b><p>${esc(a.task)}</p><small>${esc(a.domain||w.domain||'OIS')} · Data: ${esc(a.dataScope||'*')} · Resource: ${esc(a.resourceScope||'*')} · Checkpoint: ${esc(a.humanCheckpoint||'BEFORE_COMMIT')}</small><br><small>Được phép: ${(a.actions||[]).map(esc).join(', ')}</small></div><div>${badge(statusVi(a.status))} ${a.status==='READY'?`<button data-run-asg="${a.id}" class="primary small">Thực hiện</button>`:''}</div></div>`}).join('')||'<p class="muted">Chưa phân công AI. Cần phân công và xác định phạm vi ủy quyền trước khi gửi yêu cầu.</p>')}${card('Phân công AI có kiểm soát',`<div class="form-grid"><label>AI<select id="asg-agent">${agents.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>Nhiệm vụ<input id="asg-task" placeholder="Ví dụ: Rà soát dữ liệu và đề xuất vấn đề cần xử lý"></label><label>Miền<select id="asg-domain">${DOMAIN_REGISTRY.map(d=>`<option value="${d.id}" ${d.id===(w.domain||'OIS')?'selected':''}>${esc(labelDomain(d.id,i18n.lang))}</option>`).join('')}</select></label><label>Data scope<input id="asg-data-scope" value="${esc(w.scope?.id||'*')}"></label><label>Resource scope<input id="asg-resource-scope" value="${esc(w.scope?.id||'*')}"></label><label>Ủy quyền đến<input id="asg-valid-until" type="datetime-local"></label><label>Human checkpoint<select id="asg-checkpoint"><option>BEFORE_COMMIT</option><option>BEFORE_EXTERNAL_ACTION</option><option>BEFORE_CHANGE</option><option>ON_LOW_CONFIDENCE</option></select></label></div><button id="assign-ai">Phân công trong phạm vi trên</button> <button id="run-ready" class="primary">Cho AI thực hiện các nhiệm vụ sẵn sàng</button>`)}${card('Kết quả làm việc',w.outputs.length?w.outputs.map(o=>`<article class="output"><b>${esc(agents.find(a=>a.id===o.agentId)?.name||o.agentId)}</b>${o.type==='HUMAN_REQUEST'?'<span class="chip">Phản hồi yêu cầu mới</span>':''}<p>${esc(o.text)}</p><details><summary>Nguồn & lịch sử</summary><pre>${esc(JSON.stringify(o.evidence,null,2))}</pre></details></article>`).join(''):'<p class="muted">Chưa có kết quả.</p>')}`;
}
function importsView(){
 if(!isAdmin())return denied();
 const batches=store.get('importBatches',[]); const arts=store.get('artifacts',[]); const canSpeak=speechSupported(); const intake=work.get('WORK-DATA-INTAKE'); const provider=model.publicConfig();
 const intakeArts=arts.filter(a=>a.workItemId==='WORK-DATA-INTAKE');
 return pageHead('Nhập dữ liệu','Con người và AI cùng tiếp nhận, đọc, chuẩn hóa và kiểm tra dữ liệu trước khi commit')+
 card('Dữ liệu có cấu trúc',`<div class="import-types">${[['PERSONNEL','Nhân sự / giảng viên'],['STUDENT','Sinh viên'],['ORGANIZATION','Đơn vị tổ chức'],['FACILITY','Tòa nhà & phòng'],['ASSET','Trang thiết bị'],['INVENTORY','Vật tư']].map(([v,l])=>`<button data-import-type="${v}" class="${state.importType===v?'active':''}">${l}</button>`).join('')}</div><label class="file-drop">Chọn CSV hoặc JSON để nhập vào master data<input id="import-file" type="file" accept=".csv,.json"></label><p class="muted">CSV/JSON được kiểm tra trước; AI có thể hỗ trợ mapping, phát hiện thiếu/trùng/bất thường nhưng commit vào master data vẫn là human checkpoint.</p>`)+(state.importPreview?importPreviewCard():'')+
 card('AI đồng hành khi nhập dữ liệu',`<div class="ai-companion"><div class="speech-row"><button id="import-speech-start" class="speech-button" ${canSpeak?'':'disabled'}>🎙 Nói yêu cầu</button><button id="import-speech-stop" class="small" disabled>Dừng</button><span id="import-speech-status" class="muted">${canSpeak?'Sẵn sàng nhận giọng nói':'Trình duyệt chưa hỗ trợ nhận dạng giọng nói trực tiếp'}</span></div><label>Yêu cầu / hướng dẫn cho AI<textarea id="import-ai-request" rows="4" placeholder="Ví dụ: Đọc các tệp này, xác định loại dữ liệu, đề xuất mapping vào hồ sơ nhân sự và chỉ ra bản ghi cần con người xác nhận."></textarea></label><div id="import-speech-interim" class="speech-interim"></div><label class="file-drop">Thêm tài liệu, ảnh, âm thanh, video hoặc tệp dữ liệu<input id="artifact-files" type="file" multiple accept="image/*,audio/*,video/*,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.json,.txt,.md"></label><div class="assist-row"><button id="process-intake-artifacts">AI xử lý các tệp chưa đọc</button><button id="assist-import" class="primary">Gửi yêu cầu cho AI Nhập dữ liệu</button><span class="muted">${esc(provider.provider)} / ${esc(provider.model)}</span></div><p class="muted">AI chỉ làm việc trong Work Item “${esc(intake?.title||'Tiếp nhận dữ liệu')}” với quyền đã ủy quyền. AI được đọc/mapping/phân tích/tạo bản nháp staging; không tự commit master data.</p></div>`)+
 card('Tài liệu / hình ảnh / âm thanh / video',`<div class="artifact-grid">${intakeArts.slice(0,18).map(a=>`<div class="artifact"><b>${esc(a.name)}</b><span>${esc(a.mediaType)} · ${Math.round((a.size||0)/1024)} KB</span><small>${esc(a.processingStatus)}</small>${a.textPreview?`<small>${esc(a.textPreview.slice(0,180))}</small>`:''}${a.processingError?`<small class="error">${esc(a.processingError)}</small>`:''}<button class="small" data-process-artifact="${a.id}">AI xử lý tệp</button></div>`).join('')||'<p class="muted">Chưa có artifact.</p>'}</div>`)+
 (intake?.outputs?.length?card('Kết quả AI hỗ trợ nhập',intake.outputs.slice(0,8).map(o=>`<article class="output"><b>${esc(store.get('agents',[]).find(a=>a.id===o.agentId)?.name||o.agentId)}</b><p>${esc(o.text)}</p></article>`).join('')):'')+
 card('Lịch sử nhập',`<table><tr><th>Batch</th><th>Loại</th><th>File</th><th>Hợp lệ</th><th>Lỗi</th><th>Thời gian</th></tr>${batches.map(b=>`<tr><td>${esc(b.id)}</td><td>${esc(b.type)}</td><td>${esc(b.fileName)}</td><td>${b.valid}</td><td>${b.invalid}</td><td>${new Date(b.createdAt).toLocaleString('vi-VN')}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Chưa có batch.</td></tr>'}</table>`);
}
function importPreviewCard(){ const rows=state.importPreview||[]; const ok=rows.filter(r=>!r._errors.length).length; return card('Kiểm tra trước khi nhập',`<div class="kpis mini">${kpi('Tổng dòng',rows.length)}${kpi('Hợp lệ',ok)}${kpi('Có lỗi',rows.length-ok)}</div><div class="preview"><table><tr><th>Dòng</th><th>Thông tin</th><th>Lỗi</th></tr>${rows.slice(0,15).map(r=>`<tr><td>${r._row}</td><td>${esc(r.fullName||r.name||r.id)}</td><td>${r._errors.length?`<span class="error">${esc(r._errors.join('; '))}</span>`:'OK'}</td></tr>`).join('')}</table></div><button id="commit-import" class="primary" ${ok===0?'disabled':''}>Nhập ${ok} bản ghi hợp lệ</button>`);}
function masterView(){ if(!isAdmin())return denied(); const tabs=[['Đơn vị tổ chức',store.get('organizations',[])],['Nhân sự',store.get('personnel',[])],['Sinh viên',store.get('students',[])],['Cơ sở vật chất',store.get('facilities',[])],['Trang thiết bị',store.get('assets',[])],['Vật tư',store.get('inventory',[])]]; return pageHead('Dữ liệu nền tảng','Dữ liệu thực tại của nhà trường đã được nhập và xác nhận')+tabs.map(([name,arr])=>card(name,`<div class="master-list">${arr.slice(0,8).map(x=>`<div><b>${esc(x.fullName||x.name)}</b><span>${esc(x.employeeCode||x.studentCode||x.assetCode||x.itemCode||x.id)}</span></div>`).join('')||'<p class="muted">Chưa có dữ liệu.</p>'}</div><p class="muted">Tổng: ${arr.length}</p>`)).join('');}
function accountsView(){ if(!isAdmin())return denied(); const q=provisioning.queue(); const roles=identity.roles(); return pageHead('Người dùng & quản trị','Tạo, kích hoạt/tạm dừng tài khoản và quản trị vai trò/phạm vi')+card('Tạo tài khoản thủ công',`<div class="form-grid"><label>Họ tên<input id="new-display"></label><label>Tài khoản<input id="new-username"></label><label>Email<input id="new-email" type="email"></label><label>Mật khẩu tạm<input id="new-password" type="password" value="AnuTemp123!"></label><label>Vai trò<select id="new-role">${roles.map(r=>`<option value="${r.id}">${esc(roleLabel(r.id))}</option>`).join('')}</select></label><label>Phạm vi<input id="new-scope" value="ANU"></label></div><button id="create-user" class="primary">Tạo tài khoản</button>`)+card('Chờ tạo tài khoản từ dữ liệu',`<table><tr><th>Người</th><th>Nguồn</th><th>Vai trò gợi ý</th><th>Phạm vi</th><th>Trạng thái</th><th></th></tr>${q.map(i=>`<tr><td>${esc(i.displayName)}<br><small>${esc(i.email)}</small></td><td>${esc(i.sourceType)}</td><td>${esc(roleLabel(i.suggestedRole))}</td><td>${esc(i.suggestedScope)}</td><td>${badge(statusVi(i.status))}</td><td>${i.status==='PENDING'?`<button data-provision="${i.id}" class="primary small">Tạo tài khoản</button>`:i.generatedUsername?`<small>${esc(i.generatedUsername)}</small>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Không có yêu cầu chờ.</td></tr>'}</table>`)+card('Tài khoản hiện có',`<div class="table-scroll"><table><tr><th>Người dùng</th><th>Tài khoản</th><th>Vai trò & phạm vi</th><th>Trạng thái</th><th>Quản trị</th></tr>${identity.list().map(u=>`<tr><td>${esc(u.displayName)}<br><small>${esc(u.email||'')}</small></td><td>${esc(u.username)}</td><td>${(u.assignments||[]).map(a=>`<div>${esc(roleLabel(a.role))} · ${esc(a.scope?.id||'')}</div>`).join('')}</td><td>${badge(u.status)}</td><td><button class="small" data-toggle-user="${u.id}">${u.status==='ACTIVE'?'Tạm dừng':'Kích hoạt'}</button> <button class="small" data-add-role="${u.id}">Thêm vai trò</button> <button class="small" data-reset-user="${u.id}">Đặt lại mật khẩu</button></td></tr>`).join('')}</table></div>`)+card('AI cùng quản trị truy cập',`<p>AI Quản trị truy cập có thể đọc và phân tích tài khoản/quyền, phát hiện bất thường và đưa khuyến nghị. AI không tự cấp, thu hồi hoặc mở rộng quyền.</p><button data-open-work="WORK-SYS-GOV" class="primary">Mở công việc rà soát cùng AI</button>`);}
function researchView(){return pageHead(role()==='RESEARCHER'?'Đề tài & phân tích':'Nghiên cứu','Theo dõi đề tài, dữ liệu, bằng chứng và công việc đang thực hiện')+card('Đề tài trọng điểm',`<div class="project"><b>AI trong giáo dục kỹ thuật</b><span>Tiến độ 68%</span><div class="progress"><i style="width:68%"></i></div></div><div class="project"><b>Năng lực AI-Native University</b><span>Tiến độ 42%</span><div class="progress"><i style="width:42%"></i></div></div>`)+card('Công việc nghiên cứu',`<table><tr><th>Công việc</th><th>Ưu tiên</th><th>Trạng thái</th><th>Hạn</th><th>AI tham gia</th></tr>${workRows(visibleWork())}</table>`);}
function knowledgeView(){return pageHead('Tri thức & bằng chứng','Tìm và sử dụng tri thức phù hợp với phạm vi hiện hành')+card('Tri thức hiện có',store.get('knowledge',[]).map(k=>`<article class="knowledge"><b>${esc(k.title)}</b><p>${esc(k.text)}</p><small>Chủ sở hữu: ${esc(k.owner)}</small></article>`).join(''));}
function teachingView(){return pageHead('Giảng dạy','Lớp học, học liệu, sinh viên và nhiệm vụ')+`<div class="kpis">${kpi('Lớp phụ trách',4)}${kpi('Sinh viên',126)}${kpi('Bài cần chấm',14)}${kpi('Phản hồi mới',5)}</div>`+card('Lịch hôm nay','<div class="timeline"><div><b>08:00</b> AI cơ sở · A101</div><div><b>13:30</b> Hướng dẫn đồ án · Lab AI</div></div>');}
function learningView(){return pageHead('Môn học & nhiệm vụ','Theo dõi việc học và các nhiệm vụ cần hoàn thành')+card('Môn học',`<div class="grid2"><div><b>Học máy</b><p>Tiến độ 71%</p></div><div><b>Lập trình AI</b><p>Tiến độ 58%</p></div></div>`)+card('Nhiệm vụ sắp tới','<ul><li>Nộp bài Học máy · 25/09</li><li>Chuẩn bị seminar · 28/09</li></ul>');}
function domainsView(){ const counts=Object.fromEntries(domainCounts(store).map(x=>[x.id,x.count])); return pageHead('Miền vận hành','Một Đại học, nhiều miền nghiệp vụ, dùng chung Identity, Intelligence Fabric, Trust và University Memory')+`<div class="domain-grid">${DOMAIN_REGISTRY.map(d=>`<section class="card domain-card"><div class="domain-code">${d.id}</div><h3>${esc(labelDomain(d.id,i18n.lang))}</h3><p>${esc(d.description?.[i18n.lang]||d.description?.vi)}</p><div class="kpi-inline"><b>${counts[d.id]||0}</b><span>bản ghi liên quan</span></div><small>AI mặc định: ${d.defaultAgents.map(id=>esc(store.get('agents',[]).find(a=>a.id===id)?.name||id)).join(' · ')}</small></section>`).join('')}</div>`+card('Nguyên tắc dữ liệu dùng chung','<p>Person, Identity, Organization, Role, Authority, Work Item, Artifact và Evidence thuộc University Core. LIS/RIS/SIS/PIS/OIS/FIS/FMS chỉ giữ quan hệ nghiệp vụ, không tạo bản sao con người hay danh tính riêng.</p>');}
function dataReadiness(){ const domains=[['organizations','Đơn vị'],['personnel','Nhân sự'],['students','Sinh viên'],['facilities','Cơ sở vật chất'],['assets','Trang thiết bị'],['inventory','Vật tư'],['programs','Chương trình'],['courses','Học phần'],['researchProjects','Đề tài']]; return domains.map(([k,label])=>({key:k,label,count:store.get(k,[]).length,live:store.get(k,[]).some(x=>x.source==='import')})); }
function dataView(){ const issues=dataIssues(); const full=['RECTOR','VICE_RECTOR'].includes(role()); const readiness=dataReadiness(); return pageHead('Dữ liệu',full?'Dữ liệu toàn trường phục vụ điều hành và quyết định':'Dữ liệu phục vụ công việc trong phạm vi hiện hành')+`<div class="kpis">${kpi('Đơn vị tổ chức',store.get('organizations',[]).length)}${kpi('Nhân sự',store.get('personnel',[]).length)}${kpi('Sinh viên',store.get('students',[]).length)}${kpi('Cơ sở vật chất',store.get('facilities',[]).length)}${kpi('Trang thiết bị',store.get('assets',[]).length)}${kpi('Vật tư',store.get('inventory',[]).length)}${kpi('Vấn đề chất lượng',issues.length)}</div>`+card('Mức sẵn sàng dữ liệu',`<div class="readiness">${readiness.map(d=>`<div><b>${esc(d.label)}</b><span>${d.count}</span><small>${d.live?'Có dữ liệu nhập thực':'Chưa có dữ liệu nhập thực; đang hiển thị dữ liệu mẫu nếu có'}</small></div>`).join('')}</div><p class="muted">Dữ liệu mẫu chỉ dùng để thử nghiệm giao diện. Dữ liệu sống của trường phải được nhập/đồng bộ từ nguồn chính thức.</p>`)+card('Đơn vị & chức năng',store.get('organizations',[]).map(o=>`<article class="knowledge"><b>${esc(o.name)}</b><p>${esc((o.functions||[]).join(' · '))}</p><small>${esc((o.responsibilities||[]).join(' · '))}</small></article>`).join(''))+card('Vấn đề cần chú ý',issues.length?issues.map(x=>`<div class="issue">${esc(x)}</div>`).join(''):'<p>Không phát hiện vấn đề nổi bật.</p>');}
function peopleView(){return pageHead('Nhân sự','Nhân sự thuộc phạm vi đơn vị')+card('Danh sách',`<table><tr><th>Mã</th><th>Họ tên</th><th>Đơn vị</th><th>Chức vụ</th></tr>${store.get('personnel',[]).map(p=>`<tr><td>${esc(p.employeeCode)}</td><td>${esc(p.fullName)}</td><td>${esc(p.unit)}</td><td>${esc(p.position)}</td></tr>`).join('')}</table>`);}
function settingsView(){ if(!canConfigureAI(role())) return pageHead(t('settings.title'),t('settings.adminOnly')); const c=model.publicConfig(); const providerOpts=[['mock','Mô phỏng'],['openai','OpenAI'],['openrouter','OpenRouter'],['gemini','Google Gemini'],['custom','OpenAI-compatible / Custom']]; return pageHead(t('settings.title'),t('settings.subtitle'))+card('Nhà cung cấp',`<div class="form-grid"><label>Provider<select id="provider">${providerOpts.map(([v,l])=>`<option value="${v}" ${c.provider===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Model<input id="model" value="${esc(c.model)}"></label><label>API key<input id="api-key" type="password" placeholder="Chỉ giữ trong tab hiện tại"></label><label>Base URL<input id="base-url" value="${esc(c.baseUrl||'')}" placeholder="Để trống để dùng endpoint mặc định"></label><label>Giới hạn token<input id="max-tokens" type="number" value="${esc(c.maxTokens)}"></label></div><div class="action-row"><button id="save-model" class="primary">Áp dụng</button><button id="test-model">Kiểm tra kết nối</button><button id="test-inference">Kiểm tra AI thực</button></div><div id="ai-test-result" class="muted"></div><p class="muted">Provider đã chọn sẽ được dùng thật. Nếu kết nối/model lỗi, hệ thống báo lỗi rõ ràng và không tự chuyển sang mô phỏng.</p><p><b>${esc(t('provider.health'))}:</b> ${esc(c.health||'UNKNOWN')} ${c.lastTest?`· ${esc(c.lastTest)}`:''}${c.lastError?`<br><span class="error">${esc(c.lastError)}</span>`:''}</p>`);} 
function auditView(){ if(!isAdmin())return denied(); return pageHead('Nhật ký hệ thống','Ai làm gì, AI nào thực hiện, trên công việc nào và trong phạm vi nào')+card('Sự kiện gần đây',`<table><tr><th>Thời gian</th><th>Chủ thể</th><th>Hành động</th><th>Đối tượng</th></tr>${audit.list().slice(0,100).map(e=>`<tr><td>${new Date(e.timestamp).toLocaleString('vi-VN')}</td><td>${esc(e.actorId||e.agent||'')}</td><td>${esc(e.action)}</td><td>${esc(e.resourceId||'')}</td></tr>`).join('')}</table>`)+card('Lịch sử AI thực hiện',store.get('traces',[]).slice(0,30).map(t=>`<details><summary>${esc(t.timestamp)} · ${esc(t.executedBy)} · ${esc(t.status)}</summary><pre>${esc(JSON.stringify(t,null,2))}</pre></details>`).join('')||'<p class="muted">Chưa có lịch sử.</p>');}
function advancedView(){ if(!isAdmin())return denied(); return pageHead('Cấu hình nâng cao','Dành cho quản trị kỹ thuật; không phải giao diện nghiệp vụ')+card('AI đang hoạt động',`<table><tr><th>AI</th><th>Chủ sở hữu</th><th>Năng lực</th><th>Trạng thái</th></tr>${store.get('agents',[]).map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.owner)}</td><td>${a.capabilities.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</td><td>${esc(a.status)}</td></tr>`).join('')}</table>`)+card('Năng lực hệ thống',`<table><tr><th>Năng lực</th><th>Mô tả</th><th>Thẩm quyền</th></tr>${store.get('capabilities',[]).map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.name)}</td><td>${esc(c.authority)}</td></tr>`).join('')}</table>`);}
function denied(){return pageHead('Không có quyền','Vai trò hiện hành không được phép truy cập chức năng này.');}
function dataIssues(){const out=[]; for(const p of store.get('personnel',[]))if(!p.email)out.push(`Nhân sự ${p.fullName||p.employeeCode} thiếu email`); for(const s of store.get('students',[]))if(!s.email)out.push(`Sinh viên ${s.fullName||s.studentCode} thiếu email`); for(const f of store.get('facilities',[]))if((f.area===0||f.grossArea===0)&&f.type==='ROOM')out.push(`${f.name} chưa có diện tích`); for(const a of store.get('assets',[]))if(!a.location)out.push(`${a.name} chưa có vị trí`); for(const i of store.get('inventory',[]))if(Number(i.quantityOnHand)<0)out.push(`${i.name} có tồn kho âm`); return out;}
function bind(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
 document.querySelectorAll('[data-open-work]').forEach(b=>b.onclick=()=>{state.view='work';state.selectedWork=b.dataset.openWork;render()});
 $('#back-work')?.addEventListener('click',()=>{state.selectedWork=null;render()});
 $('#create-work')?.addEventListener('click',()=>{const title=$('#w-title').value.trim(); if(!title)return alert('Nhập tên công việc'); const w=work.create({title,purpose:$('#w-purpose').value.trim(),humanOwner:state.user.id,scope:{type:ctx().scope.type,id:$('#w-scope').value.trim()||ctx().scope.id},domain:$('#w-domain')?.value||'OIS',deadline:$('#w-deadline').value,expectedOutcome:''}); state.selectedWork=w.id;render()});
 $('#assign-ai')?.addEventListener('click',()=>{const agent=store.get('agents',[]).find(a=>a.id===$('#asg-agent').value); if(!agent)return; work.assign(state.selectedWork,{agentId:agent.id,task:$('#asg-task').value.trim()||'Thực hiện phần việc được giao',capabilities:agent.capabilities,actions:agent.defaultActions,domain:$('#asg-domain')?.value||'OIS',dataScope:$('#asg-data-scope')?.value||'*',resourceScope:$('#asg-resource-scope')?.value||'*',validUntil:$('#asg-valid-until')?.value?new Date($('#asg-valid-until').value).toISOString():null,humanCheckpoint:$('#asg-checkpoint')?.value||'BEFORE_COMMIT',delegatedBy:state.user.id});render()});
 document.querySelectorAll('[data-run-asg]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Đang thực hiện…';try{await multi.runAssignment({workId:state.selectedWork,assignmentId:b.dataset.runAsg,human:state.user,userContext:ctx()});render()}catch(e){alert(e.message);render()}});
 $('#run-ready')?.addEventListener('click',async()=>{try{await multi.runReady({workId:state.selectedWork,human:state.user,userContext:ctx()});render()}catch(e){alert(e.message)}});
 document.querySelectorAll('[data-import-type]').forEach(b=>b.onclick=()=>{state.importType=b.dataset.importType;state.importPreview=null;render()});
 $('#import-file')?.addEventListener('change',async e=>{const file=e.target.files[0]; if(!file)return; try{const raw=await importer.readFile(file); const normalized=importer.normalize(state.importType,raw); state.importPreview=importer.validate(state.importType,normalized); state.importFileName=file.name;render()}catch(err){alert(err.message)}});
 $('#commit-import')?.addEventListener('click',()=>{const batch=importer.commit({type:state.importType,rows:state.importPreview,userId:state.user.id,fileName:state.importFileName}); state.importPreview=null; alert(`Đã nhập ${batch.valid} bản ghi. ${batch.invalid} bản ghi lỗi không được nhập.`);render()});
 document.querySelectorAll('[data-provision]').forEach(b=>b.onclick=()=>{try{const u=provisioning.createAccount(b.dataset.provision,state.user.id); alert(`Đã tạo tài khoản ${u.username}\nMật khẩu tạm thời: ${u.password}\nHãy ghi nhận và đổi mật khẩu khi triển khai production.`);render()}catch(e){alert(e.message)}});
 $('#artifact-files')?.addEventListener('change',async e=>{for(const file of [...e.target.files]){try{const a=await artifacts.ingest(file,{uploadedBy:state.user.id,workItemId:'WORK-DATA-INTAKE',domain:'OIS'});work.attachArtifact('WORK-DATA-INTAKE',a.id);}catch(err){alert(err.message)}}render()});
 $('#work-files')?.addEventListener('change',async e=>{for(const file of [...e.target.files]){try{const a=await artifacts.ingest(file,{uploadedBy:state.user.id,workItemId:state.selectedWork,domain:work.get(state.selectedWork)?.domain||'OIS'});work.attachArtifact(state.selectedWork,a.id);}catch(err){alert(err.message)}}render()});
 document.querySelectorAll('[data-process-artifact]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Đang xử lý…';try{await multimodal.process(b.dataset.processArtifact,{prompt:'Đọc/quan sát tệp này để hỗ trợ công việc hiện tại. Trích xuất dữ kiện, cấu trúc, nội dung chính và nêu giới hạn.'});render()}catch(e){alert(`Không xử lý được tệp: ${e.message}`);render()}});
 $('#process-intake-artifacts')?.addEventListener('click',async()=>{const w=work.get('WORK-DATA-INTAKE'); if(!w)return; const active=(w.assignments||[]).filter(x=>x.status!=='REVOKED'); if(!active.some(x=>(x.actions||[]).includes('READ_FILE')))return alert('AI Nhập dữ liệu chưa được ủy quyền READ_FILE.'); for(const id of (w.artifactIds||[])){const a=artifacts.get(id);if(a&&!['TEXT_EXTRACTED','AI_PROCESSED'].includes(a.processingStatus)){try{await multimodal.process(id,{prompt:$('#import-ai-request')?.value.trim()||'Đọc dữ liệu này và chuẩn bị cho bước mapping/kiểm tra chất lượng.'});}catch(e){alert(`${a.name}: ${e.message}`);}}} render();});
 const importSpeechStart=$('#import-speech-start'), importSpeechStop=$('#import-speech-stop');
 importSpeechStart?.addEventListener('click',()=>{const box=$('#import-ai-request'),status=$('#import-speech-status'),interim=$('#import-speech-interim');try{speech.setLanguage(speechLocale());state.importInputSource='VOICE';speech.start({onStatus:v=>{if(status)status.textContent=v==='LISTENING'?'Đang nghe…':'Đã dừng nghe';if(importSpeechStart)importSpeechStart.disabled=v==='LISTENING';if(importSpeechStop)importSpeechStop.disabled=v!=='LISTENING';},onInterim:x=>{if(interim)interim.textContent=x;},onFinal:x=>{if(box){box.value=((box.value.trim()?box.value.trim()+' ':'')+x).trim();}if(interim)interim.textContent='';},onError:e=>{if(status)status.textContent=`Lỗi giọng nói: ${e}`;}});}catch(e){alert(e.message)}});
 importSpeechStop?.addEventListener('click',()=>speech.stop());
 $('#import-ai-request')?.addEventListener('input',()=>{state.importInputSource='TEXT';});
 $('#assist-import')?.addEventListener('click',async()=>{const b=$('#assist-import'),w=work.get('WORK-DATA-INTAKE');if(!w)return;let text=$('#import-ai-request')?.value.trim()||'';if(!text&&(w.artifactIds||[]).length)text='Đọc các dữ liệu/tài liệu đã nhận, đề xuất mapping, phát hiện lỗi chất lượng và chuẩn bị dữ liệu staging; không commit khi chưa có con người xác nhận.';if(!text)return alert('Hãy nói/nhập yêu cầu hoặc thêm tệp.');b.disabled=true;b.textContent='AI đang phối hợp…';try{const active=(w.assignments||[]).filter(x=>x.status!=='REVOKED');if(!active.some(x=>(x.actions||[]).includes('READ_FILE')))throw new Error('AI Nhập dữ liệu chưa được ủy quyền READ_FILE');for(const id of (w.artifactIds||[])){const a=artifacts.get(id);if(a&&!['TEXT_EXTRACTED','AI_PROCESSED'].includes(a.processingStatus))await multimodal.process(id,{prompt:text});}const source=state.importInputSource==='VOICE'?'VOICE':'TEXT';const a=artifacts.ingestText(text,{uploadedBy:state.user.id,workItemId:w.id,domain:'OIS',source:source==='VOICE'?'VOICE_TRANSCRIPT':'HUMAN_REQUEST',name:source==='VOICE'?'Bản ghi lời nói khi nhập dữ liệu':'Yêu cầu nhập dữ liệu'});work.attachArtifact(w.id,a.id);const req=work.addRequest(w.id,{text,source,createdBy:state.user.id,artifactId:a.id});await multi.respondToHumanRequest({workId:w.id,request:req,human:state.user,userContext:ctx()});state.importInputSource='TEXT';render();}catch(e){alert(`AI chưa xử lý được: ${e.message}`);render();}});
 const speechStart=$('#speech-start'); const speechStop=$('#speech-stop');
 speechStart?.addEventListener('click',()=>{
   const box=$('#work-request'); const status=$('#speech-status'); const interim=$('#speech-interim');
   try{
     speech.setLanguage(speechLocale()); state.workInputSource='VOICE';
     speech.start({
       onStatus:v=>{if(status)status.textContent=v==='LISTENING'?'Đang nghe… hãy nói yêu cầu của bạn':'Đã dừng nghe'; if(speechStart)speechStart.disabled=v==='LISTENING'; if(speechStop)speechStop.disabled=v!=='LISTENING';},
       onInterim:text=>{if(interim)interim.textContent=text;},
       onFinal:text=>{if(!box)return; const prefix=box.value.trim()?box.value.trim()+' ':''; box.value=(prefix+text).trim(); if(interim)interim.textContent='';},
       onError:err=>{if(status)status.textContent=`Không nhận được giọng nói: ${err}`; if(speechStart)speechStart.disabled=false; if(speechStop)speechStop.disabled=true;}
     });
   }catch(e){alert(e.message==='SPEECH_RECOGNITION_UNSUPPORTED'?'Trình duyệt này chưa hỗ trợ nhận dạng giọng nói trực tiếp. Có thể dùng Chrome/Edge hoặc tải tệp âm thanh lên.':e.message);}
 });
 speechStop?.addEventListener('click',()=>speech.stop());
 $('#work-request')?.addEventListener('input',()=>{state.workInputSource='TEXT';});
 $('#assist-work')?.addEventListener('click',async()=>{
   const b=$('#assist-work'); const current=work.get(state.selectedWork); if(!current)return;
   let text=$('#work-request')?.value.trim()||'';
   if(!text && (current.artifactIds||[]).length) text='Hãy đọc và phân tích các dữ liệu/tài liệu đính kèm có thể truy cập, sau đó nêu các phát hiện chính, giới hạn và đề xuất việc cần con người xử lý.';
   if(!text)return alert('Hãy nói hoặc nhập yêu cầu cho AI, hoặc đính kèm tài liệu.');
   b.disabled=true; b.textContent='AI đang phối hợp…';
   try{
     const source=state.workInputSource==='VOICE'?'VOICE':'TEXT';
     const a=artifacts.ingestText(text,{uploadedBy:state.user.id,workItemId:state.selectedWork,domain:current.domain||'OIS',source:source==='VOICE'?'VOICE_TRANSCRIPT':'HUMAN_REQUEST',name:source==='VOICE'?'Bản ghi lời nói':'Yêu cầu của con người'});
     work.attachArtifact(state.selectedWork,a.id);
     const req=work.addRequest(state.selectedWork,{text,source,createdBy:state.user.id,artifactId:a.id});
     const active=(current.assignments||[]).filter(x=>x.status!=='REVOKED'); const canRead=active.some(x=>(x.actions||[]).some(y=>['READ','READ_FILE','ANALYZE'].includes(y)));
     if(canRead){for(const id of (current.artifactIds||[])){const art=artifacts.get(id);if(art&&!['TEXT_EXTRACTED','AI_PROCESSED'].includes(art.processingStatus)){try{await multimodal.process(id,{prompt:text});}catch(err){console.warn('Artifact processing:',err.message);}}}}
     await multi.respondToHumanRequest({workId:state.selectedWork,request:req,human:state.user,userContext:ctx()});
     state.workInputSource='TEXT'; render();
   }catch(e){alert(`AI chưa xử lý được yêu cầu: ${e.message}`); b.disabled=false; b.textContent='Gửi yêu cầu cho AI đang tham gia';}
 });
 $('#create-user')?.addEventListener('click',()=>{try{const roleId=$('#new-role').value;const r=identity.roles().find(x=>x.id===roleId);const scope=$('#new-scope').value.trim()||'ANU';const u=identity.create({username:$('#new-username').value.trim(),password:$('#new-password').value,displayName:$('#new-display').value.trim(),email:$('#new-email').value.trim(),assignment:{id:`RA-${Date.now()}`,role:roleId,tier:r?.tier??3,scope:{type:roleId==='RECTOR'||roleId==='VICE_RECTOR'?'UNIVERSITY':'CONTEXT',id:scope},authority:[],dataScopes:['RECTOR','VICE_RECTOR'].includes(roleId)?['*']:[scope],validFrom:new Date().toISOString().slice(0,10),validUntil:null,status:'ACTIVE'}});audit.record({actorId:state.user.id,action:'USER_CREATE',resourceId:u.id});alert(`Đã tạo ${u.username}`);render()}catch(e){alert(e.message)}});
 document.querySelectorAll('[data-toggle-user]').forEach(b=>b.onclick=()=>{const u=identity.get(b.dataset.toggleUser);if(!u)return;u.status==='ACTIVE'?identity.suspend(u.id):identity.activate(u.id);audit.record({actorId:state.user.id,action:u.status==='ACTIVE'?'USER_ACTIVATE':'USER_SUSPEND',resourceId:u.id});render()});
 document.querySelectorAll('[data-add-role]').forEach(b=>b.onclick=()=>{const roleId=prompt('Role ID: '+identity.roles().map(r=>r.id).join(', '));if(!roleId)return;const r=identity.roles().find(x=>x.id===roleId);if(!r)return alert('Role không hợp lệ');const scope=prompt('Phạm vi','ANU')||'ANU';try{identity.addAssignment(b.dataset.addRole,{id:`RA-${Date.now()}`,role:roleId,tier:r.tier,scope:{type:['RECTOR','VICE_RECTOR'].includes(roleId)?'UNIVERSITY':'CONTEXT',id:scope},authority:[],dataScopes:['RECTOR','VICE_RECTOR'].includes(roleId)?['*']:[scope],validFrom:new Date().toISOString().slice(0,10),validUntil:null,status:'ACTIVE'});audit.record({actorId:state.user.id,action:'ROLE_ASSIGN',resourceId:b.dataset.addRole,role:roleId,scope});render()}catch(e){alert(e.message)}});
 document.querySelectorAll('[data-reset-user]').forEach(b=>b.onclick=()=>{const p=prompt('Mật khẩu mới (>=8 ký tự)');if(!p)return;try{identity.resetPassword(b.dataset.resetUser,p);audit.record({actorId:state.user.id,action:'PASSWORD_ADMIN_RESET',resourceId:b.dataset.resetUser});alert('Đã đặt lại mật khẩu');}catch(e){alert(e.message)}});
 $('#save-model')?.addEventListener('click',()=>{model.setConfig({provider:$('#provider').value,model:$('#model').value.trim(),apiKey:$('#api-key').value,baseUrl:$('#base-url').value.trim(),maxTokens:Number($('#max-tokens').value)});alert('Đã áp dụng cho tab hiện tại.');render()});

 $('#test-model')?.addEventListener('click',async()=>{const b=$('#test-model');b.disabled=true;b.textContent='Đang kiểm tra…';try{await model.testConnection();alert('Kết nối thành công');}catch(e){alert(`Kết nối thất bại: ${e.message}`);}render();});
 $('#test-inference')?.addEventListener('click',async()=>{const b=$('#test-inference');b.disabled=true;b.textContent='Đang gọi AI…';try{const r=await model.testInference();alert(`AI thực phản hồi qua ${r.provider} / ${r.model} (${r.latencyMs} ms):\n${r.text}`);}catch(e){alert(`AI chưa chạy được: ${e.message}`);}render();});
}
function render(){ if(!state.user)return login(); if(state.view==='settings'&&!canConfigureAI(role())) state.view='dashboard'; const views={dashboard,work:workView,imports:importsView,master:masterView,accounts:accountsView,domains:domainsView,research:researchView,knowledge:knowledgeView,teaching:teachingView,learning:learningView,data:dataView,people:peopleView,settings:settingsView,audit:auditView,advanced:advancedView}; shell((views[state.view]||dashboard)()); }
await i18n.init(); state.lang=i18n.lang; render();
